"""USER

Revision ID: 181fa310f3f4
Revises: b4661055f01b
Create Date: 2024-03-23 16:52:51.653267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '181fa310f3f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # commands auto generated by Alembic - please adjust! ###
    #op.add_column('user', sa.Column('id', sa.Integer(), primary_key=True))
    #op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    #op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    #op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_superuser')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'id')
    # ### end Alembic commands ###
